from_healthy = {
    "almond butter": "peanut butter",
    "almond milk": "milk",
    "almonds": "croutons",
    "arrowroot powder": "corn starch",
    "avocado": "cheese",
    "toast": "bagels",
    "red wine": "beef stock",
    "chia seeds": "breadcrumbs",
    "white wine": "chicken stock",
    "cocoa nibs": "chocolate chips",
    "coconut cream": "heavy cream",
    "coconut flour": "flour",
    "coconut oil": "vegetable oil",
    "cane sugar": "white sugar",
    "corn tortilla": "flour tortilla",
    "corn tortillas": "flour tortillas",
    "egg whites": "eggs",
    "egg white": "egg",
    "fruit-infused water": "fruit juice",
    "himalayan salt": "salt",
    "honey": "corn syrup",
    "hummus": "mayonnaise",
    "kale chips": "chips",
    "avocado butter": "butter",
    "mashed cauliflower": "mashed potatoes",
    "milk": "creamer",
    "olive oil and vinegar": "dressing",
    "palm shortening": "shortening",
    "quinoa": "white rice",
    "smashed avocado": "jelly",
    "whole-grain pasta": "pasta",
    "whole-grain spaghetti": "spaghetti",
    "whole wheat bread": "white bread",
    "zucchini noodles": "noodles"
}
