to_chinese = {
    "extra-virgin olive oil": "peanut oil",
    "olive oil": "peanut oil",
    "vegetable oil": "peanut oil",
    "canola oil": "peanut oil",
    "peanut oil": "peanut oil",
    "coconut oil": "peanut oil",
    "corn oil": "peanut oil",
    "sunflower oil": "peanut oil",
    "spaghetti pasta": "lo mein",
    "linguine pasta": "lo mein",
    "pasta": "lo mein",
    "spaghetti": "lo mein",
    "penne": "lo mein",
    "penne pasta": "lo mein",
    "vinegar": "black vinegar",
    "red pepper flakes": "dried chili pepper",
    "italian parsley": "cilantro",
    "parmesan cheese": "fermented bean curd",
    "cheddar cheese": "fermented bean curd",
    "parmesan": "fermented bean curd",
    "mushrooms": "shiitake mushrooms",
    "salad": "malatang",
    "quesadilla": "xian bing",
    "burger": "chinese hamburger",
    "pancake": "jian bing",
    "meat sauce": "da lu mian",
    "churro": "you tiao",
    "pizza": "scallion pancake",
    "wine": "shaoxing wine",
    "chicken nuggets": "chicken balls",
    "jerky": "bak kwa",
    "pork": "mapo doufu",
    "meat": "bakkwa",
    "lamb": "lamb broth",
    "pasta sauce": "hoisin sauce",
    "spaghetti sauce": "hoisin sauce",
    "shrimp": "cha jang mein",
    "tofu": "mapo tofu",
    "white rice": "jasmine scented rice",
    "corn": "bok choy",
    "ice cream": "baobing",
    "sausage": "lap ceung",
    "salsa": "mala sauce",
    "maple syrup": "chinese mala syrup",
    "panko bread crumbs": "sesame seeds",

    "fork": "chopsticks",
    "frying pan": "wok",
    "saucepan": "wok",
    "pan": "wok",
    "skillet": "wok",
    "rice cooker": "donabe",
    "cooker": "donabe",
    "spatula": "chuan",
    "ladle": "hoak",
    "pot": "wok",
    "steamers": "bamboo steamers",
    "italian": "Chinese"
}
