to_healthy = {
    "peanut butter": "almond butter",
    "milk": "almond milk",
    "croutons": "almonds",
    "corn starch": "arrowroot powder",
    "cheese": "avocado",
    "bagels": "toast",
    "beef stock": "red wine",
    "breadcrumbs": "chia seeds",
    "chicken stock": "white wine",
    "chocolate chips": "cocoa nibs",
    "heavy cream": "coconut cream",
    "flour": "coconut flour",
    "vegetable oil": "coconut oil",
    "white sugar": "cane sugar",
    "flour tortilla": "corn tortilla",
    "flour tortillas": "corn tortillas",
    "eggs": "egg whites",
    "egg": "egg white",
    "fruit juice": "fruit-infused water",
    "salt": "himalayan salt",
    "corn syrup": "honey",
    "mayo": "hummus",
    "mayonnaise": "hummus",
    "pretzels": "kale chips",
    "butter": "avocado butter",
    "mashed potatoes": "mashed cauliflower",
    "creamer": "milk",
    "ranch dressing": "olive oil and vinegar",
    "dressing": "olive oil and vinegar",
    "shortening": "palm shortening",
    "popcorn": "kale chips",
    "potato chips": "kale chips",
    "chips": "kale chips",
    "white rice": "quinoa",
    "jam": "smashed avocado",
    "jelly": "smashed avocado",
    "splenda": "cane sugar",
    "pasta": "whole-grain pasta",
    "spaghetti": "whole-grain spaghetti",
    "white bread": "whole wheat bread",
    "noodles": "zucchini noodles"
}
