to_mexican = {
    'beef': 'carne asada',
    'steak': 'carne asada',
    'fish': 'chicken',
    'bread': 'tortilla',
    'flour tortillas': 'corn tortillas',
    'potatoes': 'pinto beans',
    'basil': 'cilantro',
    'parsley': 'cilantro',
    'bell pepper': 'poblano pepper',
    'string bean': 'kidney bean',
    'peas': 'black beans',
    'turnip': 'corn',
    'carrot': 'corn',
    'eggplant': 'tomato',
    'leek': 'onion',
    'mushrooms': 'green peppers',
    'parmesan cheese': 'queso fresco',
    'cheddar cheese': 'queso fresco',
    'american cheese': 'queso fresco',
    'swiss cheese': 'queso fresco',
    'goat cheese': 'queso fresco',
    'lemon': 'lime',
    'lemon juice': 'lime juice',
    'coriander': 'paprika',
    'turmeric': 'paprika',
    'teriyaki sauce': 'black mole sauce',
    'ginger root': 'habanero',
    'ginger': 'habanero',
    'olives': 'jalapenos',
    "extra-virgin olive oil": "vegetable oil",
    'olive oil': "vegetable oil",
    "spinach": "mexican spinach",
    "sweet potato": "refried beans",
    "potato": "pinto bean",
    "maple sauce": " sweet salsa",
    "soy sauce": "soy salsa",
    "barbeque sauce": "spicy salsa",
    "marinara sauce": "salsa",
    "sauce": "salsa",
    "italian": "Mexican"
}
