vegetarian = {
    "ground beef sirloin": "lentils",
    "ground beef": "lentils",
    "ground lamb": "portobello mushrooms",
    "ground meat": "textured soy protein",
    "ground pork sausage": "veggie sausage",
    "ground pork": "textured soy protein",
    "ground turkey": "textured soy protein",
    "anchovy paste": "umeboshi paste",
    "anchovy": "umeboshi paste",
    "anchovie": "umeboshi paste",
    "bacon": "veggie bacon",
    "beef broth": "mushroom broth",
    "beef stock": "mushroom broth",
    "corned beef brisket": "seitan",
    "corned beef": "seitan",
    "beef": "seitan",
    "burger": "veggie burger",
    "calamari": "oyster mushrooms",
    "caviar": "tofu",
    "chicken breast": "seitan",
    "chicken broth": "vegetable broth",
    "chicken leg": "seitan",
    "chicken nuggets": "soy nuggets",
    "chicken stock": "vegetable broth",
    "chicken thigh": "seitan",
    "chicken": "seitan",
    "chorizo": "pimenton",
    "clam": "",
    "clam juice": "vegetable broth",
    "cod": "tofu",
    "crab": "tofu",
    "fish fillet": "tofu",
    "fish fingers": "tofu",
    "fish juice": "vegetable broth",
    "fish paste": "umeboshi paste",
    "fish sauce": "soy sauce",
    "fish stock": "vegan fish stock",
    "fish": "tofu",
    "jerky": "veggie jerky",
    "king prawns": "plant-based king prawns",
    "lamb": "portobello mushrooms",
    "lobster": "lobster mushrooms",
    "meatball": "veggie meatball",
    "meat ": "meat substitute ",
    "octopus": "oyster mushrooms",
    "oyster juice": "soy sauce",
    "oyster sauce": "soy sauce",
    "oyster": "oyster mushrooms",
    "pancetta": "portobello mushrooms",
    "pepperoni": "seitan",
    "pork tenderloin": "jackfruit",
    "pork loin": "jackfruit",
    "pulled pork": "jackfruit",
    "pork sausage": "veggie sausage",
    "pork": "seitan",
    "prawn": "sweet potatoes",
    "ribs": "seitan",
    "salami": "seitan",
    "salmon fillet": "marinated carrot",
    "salmon": "marinated carrot",
    "sardine": "umeboshi paste",
    "sausage": "veggie sausage",
    "scampi": "plant-based scampi",
    "shrimp": "sweet potatoes",
    "squid": "oyster mushrooms",
    "steak": "portobello mushrooms",
    "tuna": "chickpeas",
    "turkey": "tofurkey veggie roast",
}
