vegetarian = {
    "ground beef sirloin": "lentils",
    "ground beef": "lentils",
    "ground lamb": "portobello mushrooms",
    "ground meat": "textured soy protein",
    "ground pork sausage": "veggie sausage",
    "ground pork": "textured soy protein",
    "ground turkey": "textured soy protein",
    "anchovy paste": "umeboshi paste",
    "anchovy": "umeboshi paste",
    "anchovie": "umeboshi paste",
    "bacon": "quinoa",
    "beef top sirloin steak": "portobello mushroom",
    "beef bouillon": "vegetable bouillon",
    "beef broth": "mushroom broth",
    "beef stock": "mushroom broth",
    "corned beef brisket": "seitan",
    "corned beef": "seitan",
    "beef": "seitan",
    "burger": "veggie burger",
    "calamari": "oyster mushrooms",
    "caviar": "tofu",
    "fried chicken": "vegetarian fried chicken",
    "chicken bouillon": "vegetable bouillon",
    "chicken breast halves": "seitan",
    "chicken breast": "seitan",
    "chicken broth": "vegetable broth",
    "chicken leg": "seitan",
    "chicken nugget": "soy nugget",
    "chicken stock": "vegetable broth",
    "chicken thigh": "seitan",
    "chicken": "seitan",
    "chorizo": "pimenton",
    "clam": "oyster mushroom",
    "clam juice": "vegetable broth",
    "cod": "tofu",
    "crab": "tofu",
    "fish fillets": "tofu",
    "fish fillet": "tofu",
    "fish fingers": "tofu",
    "fish finger": "tofu",
    "fish juice": "vegetable broth",
    "fish paste": "umeboshi paste",
    "fish sauce": "soy sauce",
    "fish stock": "vegan fish stock",
    "fish": "tofu",
    "halibut fillets": "tofu",
    "halibut fillet": "tofu",
    "halibut": "tofu",
    "hot dog": "vegetarian hot dog",
    "jerky": "veggie jerky",
    "king prawns": "plant-based king prawns",
    "lamb": "portobello mushrooms",
    "lobster": "lobster mushrooms",
    "meatball": "veggie meatball",
    "meat ": "meat substitute ",
    "meat,": "meat substitute,",
    "meat.": "meat substitute.",
    "octopus": "oyster mushrooms",
    "oyster juice": "soy sauce",
    "oyster sauce": "soy sauce",
    "oyster": "oyster mushrooms",
    "pancetta": "portobello mushrooms",
    "pepperoni": "seitan",
    "pork bouillon": "vegetable bouillon",
    "pork chop": "seitan strip",
    "pork tenderloin": "jackfruit",
    "pork loin": "jackfruit",
    "pulled pork": "jackfruit",
    "pork sausage": "veggie sausage",
    "pork": "seitan",
    "prawn": "sweet potatoes",
    "ribs": "seitan",
    "salami": "seitan",
    "salmon fillet": "marinated carrot",
    "salmon": "marinated carrot",
    "sardine": "umeboshi paste",
    "sausage": "veggie sausage",
    "scampi": "plant-based scampi",
    "shrimp": "sweet potatoes",
    "squid": "oyster mushrooms",
    "steak": "portobello mushroom",
    "tuna": "chickpeas",
    "turkey": "tofurkey veggie roast",
    "worcestershire sauce": "soy sauce"
}

not_vegetarian = {
    "black beans": "beef",
    "cauliflower": "chicken",
    "chickpeas": "tuna",
    "edamame": "chicken",
    "eggplant": "chicken breast",
    "garbanzo beans": "tuna",
    "jackfruit": "pulled pork",
    "yellow lentils": "ground beef",
    "lentils": "ground beef",
    "lobster mushroom": "lobster",
    "meat substitute": "meat",
    "mushroom broth": "beef broth",
    "baby bella mushrooms": "turkey",
    "oyster mushroom": "oyster",
    "portobello mushrooms": "lamb",
    "mushroom": "beef",
    "vegetarian oyster sauce": "oyster sauce",
    "plant-based king prawns": "king prawns",
    "pinto beans": "chicken",
    "quinoa": "bacon",
    "chicken-style seitan": "chicken",
    "seitan beef": "beef",
    "seitan": "chicken",
    "soy nugget": "chicken nugget",
    "tempeh": "pork",
    "textured soy protein": "ground pork",
    "tsp": "ground pork",
    "textured vegetable protein": "lamb",
    "tvp": "lamb",
    "tofurkey veggie roast": "turkey",
    "tofu": "chicken",
    "umeboshi paste": "anchovie",
    "vegan fish stock": "fish stock",
    "vegan margarine": "margarine",
    "vegan yogurt": "yogurt",
    "soy milk": "milk",
    "soy yogurt": "yogurt",
    "vegetable bouillon": "chicken bouillon",
    "vegetable broth": "chicken broth",
    "vegetable stock": "chicken broth",
    "vegetarian chicken broth": "chicken broth",
    "vegetarian chicken-flavored broth": "chicken broth",
    "vegetarian fried chicken": "fried chicken",
    "vegetarian hot dog": "hot dog",
    "veggie burger": "burger",
    "veggie jerky": "jerky",
    "veggie meatball": "meatball",
    "veggie sausage": "sausage",
}
